# Generated by Django 5.2.5 on 2025-08-22 11:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('car_dekho_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cars',
            name='chassis_number',
        ),
        migrations.RemoveField(
            model_name='cars',
            name='price',
        ),
    ]
