# Generated by Django 5.2.5 on 2025-08-22 11:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('car_dekho_app', '0002_remove_cars_chassis_number_remove_cars_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cars',
            old_name='car_name',
            new_name='carName',
        ),
    ]
