# Generated by Django 5.2.5 on 2025-08-23 11:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('car_dekho_app', '0003_rename_car_name_cars_carname'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cars',
            old_name='carName',
            new_name='name',
        ),
    ]
