# Generated by Django 5.2.5 on 2025-08-23 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car_dekho_app', '0004_rename_carname_cars_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='cars',
            name='chasisnumber',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='cars',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True),
        ),
    ]
