# Generated by Django 5.2.5 on 2025-08-23 13:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('car_dekho_app', '0005_cars_chasisnumber_cars_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cars',
            old_name='chasisnumber',
            new_name='chassisnumber',
        ),
    ]
