# Generated by Django 5.2.5 on 2025-09-01 13:34

import car_dekho_app.models.cars
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car_dekho_app', '0006_rename_chasisnumber_cars_chassisnumber'),
    ]

    operations = [
        migrations.CreateModel(
            name='Showrooms',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=200)),
                ('website', models.URLField(blank=True, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='cars',
            name='chassisnumber',
            field=models.CharField(blank=True, max_length=100, null=True, validators=[car_dekho_app.models.cars.alphanumeric]),
        ),
    ]
